server:
  port: 9000
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
      - id: coaching-service
        uri: http://localhost:9001/
        predicates:
        - Path=/Coaching/**
          
      - id: Invoice-service
        uri: http://localhost:9002/
        predicates:
        - Path=/Invoice/**
        
      - id: Student-service
        uri: http://localhost:9003/
        predicates:
        - Path=/Students/**
        
      - id: Subject-service
        uri: http://localhost:9004/
        predicates:
        - Path=/Subject/**
          
